version: '3.2'

services:
  application:
    build:
      context: .
    volumes:
      - ./:/var/www
    ports:
      - 8181:5000

  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_ROOT_PASSWORD: asdasd
      MYSQL_PASSWORD: asdasd
    ports:
      - 3131:3306